// frameworks/nextra/app/[lang]/_components/framework-switcher.tsx
'use client'

import type { ChangeEvent, FC } from 'react'

type Framework = 'nextra' | 'vitepress'

const routePattern = /^(.*\/)(?:nextra|vitepress)(\/(?:en|ja)(?:\/.*)?$)/

function frameworkUrl(framework: Framework): string {
  const url = new URL(window.location.href)
  const matchedRoute = url.pathname.match(routePattern)

  if (matchedRoute) {
    url.pathname = `${matchedRoute[1]}${framework}${matchedRoute[2]}`
  } else {
    // `next dev` removes the production base path. Keep a canonical fallback
    // so the switcher also points at the assembled Pages-style preview.
    const pagePath = url.pathname.startsWith('/')
      ? url.pathname
      : `/${url.pathname}`
    url.pathname = `/docfw-cmp/${framework}${pagePath}`
  }

  return url.toString()
}

export const FrameworkSwitcher: FC<{ label: string }> = ({ label }) => {
  const handleChange = (event: ChangeEvent<HTMLSelectElement>) => {
    const framework = event.currentTarget.value as Framework

    if (framework !== 'nextra') {
      window.location.assign(frameworkUrl(framework))
    }
  }

  return (
    <label className="framework-switcher">
      <span className="x:sr-only">{label}</span>
      <select
        className="framework-switcher__select"
        aria-label={label}
        title={label}
        value="nextra"
        onChange={handleChange}
      >
        <option value="nextra">Nextra</option>
        <option value="vitepress">VitePress</option>
      </select>
    </label>
  )
}

// frameworks/vitepress/.vitepress/theme/components/FrameworkSwitcher.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useData } from 'vitepress'

type Framework = 'nextra' | 'vitepress'

const currentFramework: Framework = 'vitepress'
const frameworkSegment = /\/vitepress\/(en|ja)(?=\/|$)/

const { lang } = useData()

const label = computed(() =>
  lang.value.toLowerCase().startsWith('ja')
    ? 'フレームワークを切り替え'
    : 'Switch framework'
)

function switchFramework(event: Event) {
  const select = event.currentTarget as HTMLSelectElement
  const framework = select.value as Framework

  if (framework === currentFramework) return

  const target = new URL(window.location.href)
  const nextPathname = target.pathname.replace(
    frameworkSegment,
    `/${framework}/$1`
  )

  // Only navigate when the expected framework/locale segment is present.
  // Resetting also keeps the control truthful on an unexpected preview URL.
  if (nextPathname === target.pathname) {
    select.value = currentFramework
    return
  }

  target.pathname = nextPathname
  window.location.assign(target.href)
}
</script>

<template>
  <label class="framework-switcher">
    <span class="framework-switcher__label">{{ label }}</span>
    <select
      class="framework-switcher__select"
      :aria-label="label"
      :title="label"
      :value="currentFramework"
      @change="switchFramework"
    >
      <option value="nextra">Nextra</option>
      <option value="vitepress">VitePress</option>
    </select>
  </label>
</template>
